version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: always
    environment:
      - TZ=UTC
      # Explicitly disable proxies for the bot
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - http_proxy=
      - https_proxy=
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 