version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-parcer-bot
    restart: unless-stopped
    environment:
      # Явно отключаем все прокси
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - ALL_PROXY=
      - NO_PROXY=
      # Переменные окружения для бота
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - CHANNEL_ID=${CHANNEL_ID}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - PHONE_NUMBER=${PHONE_NUMBER}
      - MONITORING_INTERVAL_MINUTES=${MONITORING_INTERVAL_MINUTES:-5}
    volumes:
      - ./data:/app/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 