version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: always
    environment:
      - TZ=UTC
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 